### PR TITLE
Remove cats from initial libraryDependencies.

### PR DESCRIPTION
**Pull request by mtgto**
This template is used in [Getting started with scala and sbt at scala-lang.org](https://docs.scala-lang.org/getting-started-sbt-track/getting-started-with-scala-and-sbt-on-the-command-line.html#create-the-project).
Cats is unnecessary for beginner.

### CODE REVIEW

**Comment by kmizu** [comment]
@Philippus @travissarles How do you think about this pull request ? I agree with @mtgto  's opinion.

**Comment by SethTisue** [comment]
note that https://docs.scala-lang.org/getting-started-sbt-track/getting-started-with-scala-and-sbt-on-the-command-line.html uses scala-parser-combinators as a sample dependency

**Comment by SethTisue** [comment]
so I would suggest substituting that, to keep this repo aligned with the web page. note that cats is also mentioned in a subsequent comment, so that needs updating as well

**Comment by SethTisue** [comment]
anyone interested in adopting this apparently abandoned PR?

**Comment by bjornregnell** [comment]
@SethTisue Is there anything I can do to help getting this merged?

**Comment by SethTisue** [comment]
I don't think it's mergeable in its current form, as per my comments above. Happy to merge either this PR, if it is updated, or a replacement PR.

**Comment by mtgto** [comment]
@SethTisue I update to use `scala-parser-combinators` instead of `cats`.

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
